name: Node.js CI  
  
on:  
  push:  
    branches: [ main ] # Ensure this is the branch you want to trigger tests on  
  pull_request:  
    branches: [ main ]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
    - uses: actions/checkout@v2  
    - name: Use Node.js 14.x  
      uses: actions/setup-node@v2  
      with:  
        node-version: 14.x # Select the Node.js version based on your project's needs  
    - run: npm install # If your project has dependencies, this step is necessary  
    - run: npm test # Runs the test script defined in package.json